### ISSUE TITLE
改造helm部署子节点方案

### ISSUE THREAD

**Issue by zhaobei** [zhaobei/python-script#1]
#### 背景

由于子节点之间ip、db、服务对应的账号或者域名 等处不同处，导致子节点部署脚本不能够直接git clone下来进行复用，如此以来会有如下弊端：

- 多次部署以及更新子节点，会浪费时间去分别传输相应的子节点部署文件到相应的节点上去。
- 直接影响子节点的可迁徙性

#### 思路

基于此背景，决定将子节点部署脚本从某专用变为可复用的脚本，计划将子节点与子节点之间的易变量提取出来，单独放置在一个json文件中，使用python 编写脚本，部署前按需提取相应的参数，使其能够一个脚本部署多个节点，实现复用。

需要提取的变量如下：
```
# 公共配置
global:
  runMode: 
  productionName: 
  nodeID:
  beDomain: 
  feDomain: 
  mainNodeAPIURL: 

# mysql 配置
mysql:
  svcName: 
  port: 
  endpoint: 

# harbor
harbor:
  svcName: 
  username: 
  password: 
  endpoint: 
  port: 
  registryURL: 

# Redis 配置
redis:
  svcName: 
  port: 
  password: 
  endpoint: 

# Minio 配置
minio:
  svcName: 
  port: 
  accessKey: 
  secretKey: 

# jaeger 配置
jaeger:
  agentPort: 
```
#### 方案：

优化方案如下：

python:  pyyaml、os、sys、json

在原有文件节后基础上增加values.json、fill_data.py。

1、values.json 中每个节点所依赖的数据都是一个字典，由多个字典组成values.json。我们可以在values.josn中将我们我们将要部署的节点的数据填好，

2、fill_data.py负责将json中的数据进行按需处理，而后变成yaml写入values.yaml。

处理过程：

1. 读取全部json数据，根据数据python fill_data <参数> 来确定提取哪个参数
2. 将参数提取后处理成为一个字典，打开value.yaml 追加写入

- 在不确定建立多少节点的情况下，如何保证fill_data.py的灵活性？而不是只能固定创建几个节点。
- 在处理好json后，重写value.yaml还是追加写入？

### 不确定建⽴多少节点的情况下，如何保证fill_data.py的灵活性？

我们的 values.json 可以是如下格式：

```json
{
    "dopx-slave-01": {
        
    },
    "dopx-slave-02": {
        
    }
}
```

填充变量后我们执行 `python fill_data.py --node dopx-slave-01 -f values.json` 来实现一个节点数据的填充

### 在处理好json后，重写value.yaml还是追加写⼊？

可以固定一个模板 values.yaml.tmp 对所有变量 “挖洞”，每次生成新的 values.yaml

### 现在的 helm chart 之于我们的痛点

现有的 helm chart 解决不了我们同时部署多集群、更新多集群的问题。它仅在单一部署时有效

### 解决痛点的原则

我们一定是基于 helm chart 解决痛点的，而不是把 values.yaml 抛弃掉，重新构建一套我们自己的 values.json

### 建议的解决原则

1. 遵循用户使用 helm chart 的直觉，不要让 「使用 helm chart 部署」与 「使用我们的脚本部署」有太多的思维困难与转变
2. 分清哪些是：1. 部署服务所需的业务参数 2. 因为环境差异所需的环境参数

### 示例

values.yaml.tmp

```yaml

# Redis 配置
redis:
  svcName: redis
  port: <REDIS.PORT>
  password:  <REDIS.PWD>
  endpoint: <REDIS.IP>

# 业务配置
dynamicMasker:
  image: uhub.service.ucloud.cn/securityhouse/pyservice.dynamic-masker:develop-109576
  port: 31003
  protocol: TCP
  targetPort: 8000
```

values.json 

```json
{
    dopx-node1: {
        redis: {
            ip: "10.9.125.147",
            pwd: "rnj5cLQj3f",
            port: 6379
        }
    }
}
```

执行 `python fill-data.py -node dopx-node1` 生成完整 values.yaml

#### 服务变更

修改 values.yaml.tmp，该文件就是我们做一次标准部署的模板

#### 环境变更

修改 values.json，该文件是屏蔽环境差异的屏障。
